### ISSUE TITLE
Cannot execute statement and State as running forever

### ISSUE THREAD

**Issue by quanghoc** [tobilg/docker-livy#1]
I followed this doc here
https://github.com/cloudera/hue/tree/master/apps/spark/java

and created session then sent in a simple `{"code": "1+1"}` via POST `/sessions/{sessionId}/statements` but what I got was this:

```
{
  "id": 0,
  "state": "running",
  "output": null
}
```

The Kitematic console shows this

```
192.168.59.1 - - - 10/Mar/2016:07:56:26 +0000 "GET /sessions/0/statements/0 HTTP/1.1" 200 40
```

I think this has to do with Livy but I am wondering if you ever got it to work?

**Comment by tobilg** [comment]
According to the docs you'd have to call `GET /sessions/0/statements/0` until the [Statement State](https://github.com/cloudera/hue/tree/master/apps/spark/java#statement-state) is `available`. Did you do that?

Also, have a look at http://gethue.com/how-to-use-the-livy-spark-rest-job-server-for-interactive-spark-2-2/

If you want to try a JavaScript REST API for Spark, you could also have a look at [Spark-Server](https://github.com/spark-server/spark-server).

**Comment by quanghoc** [comment]
Hi,

I may be wasn't clear in previous message (The console log showed what I did). I am familiar with Livy. So basically I followed the steps:
1. Create a session
2. Get sessionId (which is 0)
3. Submit statement (return statementId which is 0)
4. Get results of that statementId 0

So GET `/sessions/0/statements/0` returned this:

```
{
  "id": 0,
  "state": "running",
  "output": null
}
```

It stuck at `running` state. Do GET `/sessions` and the whole thing still says 

```
{
  "from": 0,
  "total": 1,
  "sessions": [
    {
      "id": 0,
      "state": "busy",
      "kind": "spark",
      "log": [
        "16/03/10 23:49:23 INFO Utils: Successfully started service 'HTTP file server' on port 55451.",
        "16/03/10 23:49:23 INFO SparkContext: Added JAR file:/apps/livy/livy-assembly/target/scala-2.10/livy-assembly-0.2.0-SNAPSHOT.jar at http://172.17.0.2:55451/jars/livy-assembly-0.2.0-SNAPSHOT.jar with timestamp 1457653763665",
        "16/03/10 23:49:23 INFO Executor: Starting executor ID driver on host localhost",
        "16/03/10 23:49:23 INFO Executor: Using REPL class URI: http://172.17.0.2:58894",
        "16/03/10 23:49:23 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 57399.",
        "16/03/10 23:49:23 INFO NettyBlockTransferService: Server created on 57399",
        "16/03/10 23:49:23 INFO BlockManagerMaster: Trying to register BlockManager",
        "16/03/10 23:49:23 INFO BlockManagerMasterEndpoint: Registering block manager localhost:57399 with 517.4 MB RAM, BlockManagerId(driver, localhost, 57399)",
        "16/03/10 23:49:23 INFO BlockManagerMaster: Registered BlockManager",
        "172.17.0.2 - - - 10/Mar/2016:23:50:23 +0000 \"POST /execute HTTP/1.1\" 200 91"
      ]
    }
  ]
}
```

Have you tried the latest code from Livy? I believe this is the Livy component within Hue, correct? 

Let me know if there is a fix.

**Comment by tobilg** [comment]
Just to be clear: You tried to access `GET /sessions/0/statements/0` several times, not only once, right?

Concerning your last question, the project has apparantly been migrated from Hue to an [own Github repository](https://github.com/cloudera/livy). The Dockerfile doesn't reflect this yet.

**Comment by quanghoc** [comment]
Oh yeah, like I mentioned, the State remains "forever". It froze.

If you haven't tested this in the last few weeks or so, Livy component inside Hue no longer works.
Let me know if you can get that to work or the new Livy to work. I am still stuck :P

**Comment by tobilg** [comment]
You didn't mention directly that you tried multiple times, that's why I wanted to make sure you did... The image was build some time ago, and changes in the old repo are surely not reflected in the image.

I'll switch to the new repo and push the image to Docker Hub. As I don't have much time currently, and Livy is not one of my priorities, I'd like to ask you to test the new version. It's currently built on Docker Hub: https://hub.docker.com/r/tobilg/livy/builds/

Also, as I'm only the creator of the Docker image, I can't really help you with Livy errors etc. I'd like to ask that you refer to the project's authors for that. 

Thanks for your understanding.

**Comment by quanghoc** [comment]
I certainly did hit the /sessions/0/statements/0 multiple times. If you
didn't test it, very likely it didn't even work back then.

The newest Livy doesn't work either. So there isn't much to do until they
are more stable.

**Comment by tobilg** [comment]
The old version worked for me at least. After changing to the new repository, I couldn't get it to work either. The project doesn't have any release yet, so the Docker images rely on a sane master branch.

I just triggered a new build on Docker Hub, maybe to problems have been solved. Otherwise I'm afraid I can't help you much, because this is obviously a problem with the Livy project itself. The Docker image builds smoothly, and Livy is also compiled without errors. The problems must lie in the actual code IMHO.
